doc-warnings: false
test-warnings: false
strictness: veryhigh
max-line-length: 120
pep8:
  full: true
  disable:
    - N813

autodetect: true
requirements:
  - requirements.txt
  - requirements-dev.txt
ignore-paths:
  - data
  - docs
  - reports
  - tests
python-targets:
  - 3