language: python

os:
  - linux

python:
  - 3.4
  - 3.5
  - 3.6

cache:
  pip: false

before_install:
  - python --version
  - uname -a

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

notifications:
  email:
    on_success: never
    on_failure: email

script:
  - coverage run --source=src/ setup.py test
after_script:
  - coverage report
after_success:
    coveralls